# -*- coding: utf-8 -*-
"""Scraper

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rojcGRW0mUgbP_jNi_SHl2Z456adFFd1
"""

import requests
from bs4 import BeautifulSoup

# Function to fetch and parse HTML headings
def get_headings(url):
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    }

    try:
        response = requests.get(url, headers=headers)
        response.raise_for_status()

        soup = BeautifulSoup(response.text, "html.parser")

        headings = []
        for i in range(1, 7):  # Loop through h1 to h6
            for tag in soup.find_all(f'h{i}'):
                headings.append(tag.get_text(strip=True))

        return "\n".join(headings) if headings else "No headings found."

    except requests.exceptions.RequestException as e:
        return f"Error fetching the page: {e}"

# User input for URL
url = input("Enter the URL: ")
headings = get_headings(url)
print("\nExtracted Headings:\n")
print(headings)